// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWbN8yTrgG4bzAGQTqh5oKMoBe3J5u1c',
    appId: '1:191180345910:web:3698d90ea02f65a4cffe97',
    messagingSenderId: '191180345910',
    projectId: 'stack-9f7f6',
    authDomain: 'stack-9f7f6.firebaseapp.com',
    databaseURL: 'https://stack-9f7f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stack-9f7f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9HCfWzCw1f69iCDo3wlBLZoNb-ftspY',
    appId: '1:191180345910:android:5afed70cd9975560cffe97',
    messagingSenderId: '191180345910',
    projectId: 'stack-9f7f6',
    databaseURL: 'https://stack-9f7f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stack-9f7f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwjezbbCjTZnuOJYnKu8cEZlVoc6Tnrk',
    appId: '1:191180345910:ios:68c1247794ab1d39cffe97',
    messagingSenderId: '191180345910',
    projectId: 'stack-9f7f6',
    databaseURL: 'https://stack-9f7f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stack-9f7f6.appspot.com',
    iosBundleId: 'com.example.appGestionEspaiSalut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwjezbbCjTZnuOJYnKu8cEZlVoc6Tnrk',
    appId: '1:191180345910:ios:b9b7191df0593f9bcffe97',
    messagingSenderId: '191180345910',
    projectId: 'stack-9f7f6',
    databaseURL: 'https://stack-9f7f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stack-9f7f6.appspot.com',
    iosBundleId: 'com.example.appGestionEspaiSalut.RunnerTests',
  );
}
